server:
  port: 8083

spring:
  application:
    name: deck-service  # Name for Eureka Registration

  datasource:
    url: jdbc:mysql://localhost:3306/duel_masters
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}